import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { draftMode } from "next/headers";
import ExitDraftModeLink from "../contenful/components/ExitDraftModeLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
            afdasfdsf
          {draftMode().isEnabled && (
            <p className="bg-orange-200 py-4 px-[6vw]">
              Draft mode is on! <ExitDraftModeLink className="underline" />
            </p>
          )}
        </div>

        {children}
      </body>
    </html>
  );
}
